version: '3.8'

services:
  app-dechets:
    build: .
    container_name: poc-dechets-app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=file:/app/prisma/dev.db
    command: sh -c "npx prisma db push && npm run dev"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped

  prisma-studio:
    build: .
    container_name: poc-dechets-studio
    ports:
      - "5555:5555"
    environment:
      - DATABASE_URL=file:/app/prisma/dev.db
    volumes:
      - .:/app
      - /app/node_modules
    command: npx prisma studio --port 5555 --hostname 0.0.0.0
    restart: unless-stopped
